// Centralized database for all categories
export const categories = [
  { title: "Books", path: "books", count: "2,340 titles" },
  { title: "Sourcebooks", path: "sourcebooks", count: "1,280 titles" },
  { title: "Periodicals", path: "periodicals", count: "985 titles" },
  { title: "Thesis / Research Papers", path: "thesis", count: "760 titles" },
  { title: "Statute / Law / Legal Documents", path: "legal", count: "1,120 titles" },
  { title: "Guide / Manuals", path: "guides", count: "650 titles" },
  { title: "Report", path: "reports", count: "430 titles" },
  { title: "Reference Materials", path: "reference", count: "310 titles" },
];

// Centralized books database
export const allBooks = [
  // Books
  {
    id: "the-vanishing-half",
    title: "The Vanishing Half: A Novel",
    author: "Brit Bennett",
    isbn: "978-1-234-56789-0",
    category: "books",
    image: "/assets/BooksImages/3.jpg",
    year: 2020,
    isNew: false,
    readingAge: "Adult",
  },
  {
    id: "the-design-of-books",
    title: "The Design of Books",
    author: "Debbie Berne",
    isbn: "978-1-234-56789-0",
    category: "books",
    image: "/assets/BooksImages/4.png",
    year: 2023,
    isNew: true,
    readingAge: "Adult",
  },
  {
    id: "educated",
    title: "Educated",
    author: "Tara Westover",
    isbn: "978-1-234-56789-0",
    category: "books",
    image: "/assets/BooksImages/2.avif",
    year: 2021,
    isNew: false,
    readingAge: "Adult",
  },
  {
    id: "modern-architecture",
    title: "Modern Architecture",
    author: "Jane Doe",
    isbn: "978-1-234-56789-2",
    category: "books",
    image: "/assets/BooksImages/200.png",
    year: 2022,
    isNew: false,
    readingAge: "Adult",
  },
  {
    id: "science-today",
    title: "Science Today",
    author: "Robert Johnson",
    isbn: "978-1-234-56789-3",
    category: "books",
    image: "/assets/BooksImages/2.avif",
    year: 2021,
    isNew: false,
    readingAge: "Teen",
  },
  
  // Sourcebooks
  {
    id: "advanced-mathematics",
    title: "Advanced Mathematics Sourcebook",
    author: "Dr. Sarah Johnson",
    isbn: "978-1-234-56789-1",
    category: "sourcebooks",
    image: "/assets/BooksImages/200.png",
    year: 2023,
    isNew: true,
    readingAge: "Adult",
  },
  {
    id: "physics-laboratory",
    title: "Physics Laboratory Manual",
    author: "Prof. Michael Chen",
    isbn: "978-1-234-56789-2",
    category: "sourcebooks",
    image: "/assets/BooksImages/3.jpg",
    year: 2022,
    isNew: false,
    readingAge: "Adult",
  },
  {
    id: "historical-documents",
    title: "Historical Documents Collection",
    author: "Various Authors",
    isbn: "978-1-234-56789-3",
    category: "sourcebooks",
    image: "/assets/BooksImages/4.png",
    year: 2024,
    isNew: true,
    readingAge: "Adult",
  },

  // Periodicals
  {
    id: "science-monthly",
    title: "Science Monthly Magazine",
    author: "Science Publications",
    isbn: "978-1-234-56789-4",
    category: "periodicals",
    image: "/assets/BooksImages/2.avif",
    year: 2024,
    isNew: true,
    readingAge: "Adult",
  },
  {
    id: "daily-news",
    title: "Daily News Digest",
    author: "News Corp",
    isbn: "978-1-234-56789-5",
    category: "periodicals",
    image: "/assets/BooksImages/4.png",
    year: 2023,
    isNew: false,
    readingAge: "Adult",
  },
  {
    id: "academic-journal",
    title: "Academic Journal Quarterly",
    author: "University Press",
    isbn: "978-1-234-56789-6",
    category: "periodicals",
    image: "/assets/BooksImages/200.png",
    year: 2024,
    isNew: true,
    readingAge: "Adult",
  },

  // Thesis / Research Papers
  {
    id: "machine-learning-healthcare",
    title: "Machine Learning in Healthcare",
    author: "Dr. Emily Watson",
    isbn: "978-1-234-56789-7",
    category: "thesis",
    image: "/assets/BooksImages/200.png",
    year: 2024,
    isNew: true,
    readingAge: "Adult",
  },
  {
    id: "climate-change-study",
    title: "Climate Change Impact Study",
    author: "Prof. James Anderson",
    isbn: "978-1-234-56789-8",
    category: "thesis",
    image: "/assets/BooksImages/3.jpg",
    year: 2023,
    isNew: false,
    readingAge: "Adult",
  },
  {
    id: "quantum-computing",
    title: "Quantum Computing Research",
    author: "Dr. Lisa Zhang",
    isbn: "978-1-234-56789-9",
    category: "thesis",
    image: "/assets/BooksImages/4.png",
    year: 2024,
    isNew: true,
    readingAge: "Adult",
  },

  // Reports
  {
    id: "financial-report",
    title: "Annual Financial Report 2024",
    author: "Finance Department",
    isbn: "978-1-234-56789-10",
    category: "reports",
    image: "/assets/BooksImages/200.png",
    year: 2024,
    isNew: true,
    readingAge: "Adult",
  },
  {
    id: "market-analysis",
    title: "Market Analysis Q3 2024",
    author: "Research Team",
    isbn: "978-1-234-56789-11",
    category: "reports",
    image: "/assets/BooksImages/3.jpg",
    year: 2024,
    isNew: false,
    readingAge: "Adult",
  },
  {
    id: "technical-infrastructure",
    title: "Technical Infrastructure Report",
    author: "IT Department",
    isbn: "978-1-234-56789-12",
    category: "reports",
    image: "/assets/BooksImages/4.png",
    year: 2023,
    isNew: false,
    readingAge: "Adult",
  },

  // Legal Documents
  {
    id: "constitutional-law",
    title: "Constitutional Law Handbook",
    author: "Legal Publications",
    isbn: "978-1-234-56789-13",
    category: "legal",
    image: "/assets/BooksImages/200.png",
    year: 2024,
    isNew: true,
    readingAge: "Adult",
  },
  {
    id: "criminal-code",
    title: "Criminal Code Compendium",
    author: "Justice Department",
    isbn: "978-1-234-56789-14",
    category: "legal",
    image: "/assets/BooksImages/3.jpg",
    year: 2023,
    isNew: false,
    readingAge: "Adult",
  },
  {
    id: "civil-procedure",
    title: "Civil Procedure Guide",
    author: "Court System",
    isbn: "978-1-234-56789-15",
    category: "legal",
    image: "/assets/BooksImages/4.png",
    year: 2024,
    isNew: true,
    readingAge: "Adult",
  },

  // Guides / Manuals
  {
    id: "user-manual",
    title: "User Manual for Software Development",
    author: "Tech Publications",
    isbn: "978-1-234-56789-16",
    category: "guides",
    image: "/assets/BooksImages/200.png",
    year: 2024,
    isNew: true,
    readingAge: "Adult",
  },
  {
    id: "digital-marketing",
    title: "Complete Guide to Digital Marketing",
    author: "Marketing Experts",
    isbn: "978-1-234-56789-17",
    category: "guides",
    image: "/assets/BooksImages/3.jpg",
    year: 2023,
    isNew: false,
    readingAge: "Adult",
  },
  {
    id: "installation-manual",
    title: "Installation and Setup Manual",
    author: "Technical Support",
    isbn: "978-1-234-56789-18",
    category: "guides",
    image: "/assets/BooksImages/4.png",
    year: 2024,
    isNew: true,
    readingAge: "Adult",
  },
];

// Helper function to get books by category
export const getBooksByCategory = (categoryPath) => {
  return allBooks.filter(book => book.category === categoryPath);
};

// Helper function to get category info by path
export const getCategoryByPath = (categoryPath) => {
  return categories.find(cat => cat.path === categoryPath);
};
