// Using Nimbus Sans via CSS instead of Google Fonts
import "./globals.css";

// Font configuration moved to globals.css

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="antialiased"
        style={{ fontFamily: '"Nimbus Sans", sans-serif' }}
      >
        {children}
      </body>
    </html>
  );
}
